{ pkgs, ... } : [
  "$MOD2, N, exec, ${pkgs.google-chrome}/bin/google-chrome-stable --incognito"
  "$MOD1, N, exec, ${pkgs.google-chrome}/bin/google-chrome-stable"
  "$MOD1, RETURN, exec, ${pkgs.kitty}/bin/kitty"

  ",PRINT, exec, ${pkgs.hyprshot}/bin/hyprshot -m region --clipboard-only"
  "$MOD1, R, exec, ${pkgs.rofi-wayland}/bin/rofi -show-icons -show drun"
  "$MOD2, F, togglefloating"
  "$MOD1, J, togglesplit"
  "$MOD2, X, killactive"

  "$MOD1, w, movefocus, u"
  "$MOD1, a, movefocus, l"
  "$MOD1, s, movefocus, d"
  "$MOD1, d, movefocus, r"

  "$MOD2, apostrophe, movetoworkspace, special:magic"
  "$MOD1, apostrophe, togglespecialworkspace, magic"

  "$MOD1, 1, workspace, 1"
  "$MOD1, 2, workspace, 2"
  "$MOD1, 3, workspace, 3"
  "$MOD1, 4, workspace, 4"
  "$MOD1, 5, workspace, 5"
  "$MOD1, 6, workspace, 6"
  "$MOD1, 7, workspace, 7"
  "$MOD1, 8, workspace, 8"
  "$MOD1, 9, workspace, 9"
  "$MOD1, Q, workspace, 10"

  "$MOD2, 1, movetoworkspace, 1"
  "$MOD2, 2, movetoworkspace, 2"
  "$MOD2, 3, movetoworkspace, 3"
  "$MOD2, 4, movetoworkspace, 4"
  "$MOD2, 5, movetoworkspace, 5"
  "$MOD2, 6, movetoworkspace, 6"
  "$MOD2, 7, movetoworkspace, 7"
  "$MOD2, 8, movetoworkspace, 8"
  "$MOD2, 9, movetoworkspace, 9"
  "$MOD2, Q, movetoworkspace, 10"

  "$MOD1, F1, workspace, 11"
  "$MOD1, F2, workspace, 12"
  "$MOD1, F3, workspace, 13"
  "$MOD1, F4, workspace, 14"
  "$MOD1, F5, workspace, 15"
  "$MOD1, F6, workspace, 16"
  "$MOD1, F7, workspace, 17"
  "$MOD1, F8, workspace, 18"
  "$MOD1, F9, workspace, 19"
  "$MOD1, F10, workspace, 20"

  "$MOD2, F1, movetoworkspace, 11"
  "$MOD2, F2, movetoworkspace, 12"
  "$MOD2, F3, movetoworkspace, 13"
  "$MOD2, F4, movetoworkspace, 14"
  "$MOD2, F5, movetoworkspace, 15"
  "$MOD2, F6, movetoworkspace, 16"
  "$MOD2, F7, movetoworkspace, 17"
  "$MOD2, F8, movetoworkspace, 18"
  "$MOD2, F9, movetoworkspace, 19"
  "$MOD2, F10, movetoworkspace, 20"
]
