table inet filter {
	chain input {
		type filter hook input priority 0; policy drop;

		iifname { "lo" } accept

		ct state { established, related } accept

    tcp dport { 22, 80, 443 } accept
	}

	chain forward {
		type filter hook forward priority filter; policy drop;

		oifname { "ppp0" } accept
		ct state { established, related } accept
	}
}

table ip nat {
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		masquerade
	}
}
