set-environment -g COLORTERM "truecolor"
set -ag terminal-overrides ",$TERM:Tc"
set -g default-terminal "$TERM"
set -g xterm-keys on
set -g mouse on


bind -n M-q previous-window
bind -n M-e next-window

bind -n C-Right select-pane -R
bind -n C-Left select-pane -L
bind -n C-Down select-pane -D
bind -n C-Up select-pane -U

bind -n M-h split-window -v -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-k killp
